--- 
- 
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
  
      - name: Ensure pip3 is installed 
        apt:
          name: python3-pip 
          state: present
      
      - name: Ensure setuptools 2 is installed 
        apt:
           name: python-setuptools
           state: present 

      - name: Ensure setuptools 3 is installed 
        apt:
          name: python3-setuptools
          state: present
          

      - name: Ensure pyserial is installed with pip 3
        pip:
          name: pyserial
          executable: pip3

      - name: Ensure Pillow is installed with pip 3
        pip:
          name: Pillow
          executable: pip3

      - name: Get gonet3 repo from GitHub
        git: 
          dest: /home/pi/Tools/Camera
          repo: "https://github.com/Wied58/gonet3.git"
          update: yes
          force: yes

      - name: Change owership and permissions
        file:
           path: /home/pi/Tools/Camera
           state: directory
           owner: pi 
           group: pi
           # when specifying mode using octal numbers, add a leading 0
           mode: 0755
           recurse: yes
        
      - name: Update .bashrc
        blockinfile: 
           dest: "/home/pi/.bashrc"
           block: |
             unalias ls
             set -o vi
             alias pull_gonet='ansible-pull -d /home/pi/pull -i '\''localhost,'\'' -U https://github.com/Wied58/Update_gonet pull_gonet.yml'
   
